matrix:
  include:
  - language: rust
    name: "Rust version"
    before_script: cd AGA8CODE/RUST

  - language: cpp
    name: "C++ version"
    before_script: cd AGA8CODE/C && mkdir -p build && cd build
    script: cmake .. && cmake --build . && ctest --output-on-failure

  - language: generic
    name: "Fortran version"
    before_install: sudo apt-get install gfortran
    before_script: cd AGA8CODE/FORTRAN && mkdir -p build && cd build
    script: cmake .. && cmake --build . && ctest --output-on-failure
